Add guess tests
JorjaF/sorting_cards pull request #2
Opened 2023-04-18 19:13 UTC by JorjaF

so i added the tests for the guess class, can you take a look at them before I start coding, please?

2023-04-18 19:28 UTC, dcoleman21 requested changes
Take a look at the comments that I have left for you. Let me know what questions you have and/or bring them to your checkin tomorrow.

2023-04-18 19:28 UTC, dcoleman21 commented on spec/guess_spec.rb
> +    expect(guess).to be_instance_of(Guess)
You can add an expect here for `card` as well if you would like

2023-04-18 19:28 UTC, dcoleman21 commented on spec/guess_spec.rb
> +    guess.card
I would wrap `guess.card` in an expect
```ruby
expect(guess.card).to eq(card)
```

2023-04-18 19:28 UTC, dcoleman21 commented on spec/guess_spec.rb
> +  it 'can make a correct guess' do
Make this an `"it has attributes" do` test

2023-04-18 19:28 UTC, dcoleman21 commented on spec/guess_spec.rb
> +  it "can have an incorrect guess" do
You can put both the `correct` and `incorrect` guess in the same test. 
So you would want a test here that calls on `guess.correct?` which should return `true` or `false`. So you can set the test up to return both of those.

2023-04-18 19:28 UTC, dcoleman21 commented on spec/guess_spec.rb
> +    expect(guess.feedback).to eq("Incorrect!")
Then I would write a test 
```ruby
it 'can give feedback for a guess' do
```
Where you are testing `guess.feedback` and returning both `"Correct"` and `"Incorrect"`.

2023-04-18 21:16 UTC, JorjaF reviewed
hey i made some changes to the guess tests, can you double check them for me please?

2023-04-20 17:27 UTC, JorjaF commented on spec/guess_spec.rb
> +    guess.card
updated

2023-04-20 17:28 UTC, merged